// Core framework
global using SDK;
global using SkiaSharp;
global using System.Buffers;
global using System.Collections.Concurrent;
global using System.Diagnostics;
global using System.Numerics;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;

// Silk project namespaces
global using eft_dma_radar.Silk.Misc;
global using eft_dma_radar.Silk.Misc.Data;
global using eft_dma_radar.Silk.Misc.Input;
global using eft_dma_radar.Silk.Misc.Pools;
global using eft_dma_radar.Silk.DMA;
global using eft_dma_radar.Silk.Tarkov;
global using eft_dma_radar.Silk.Tarkov.GameWorld;
global using eft_dma_radar.Silk.Tarkov.GameWorld.Exits;
global using eft_dma_radar.Silk.Tarkov.GameWorld.Loot;
global using eft_dma_radar.Silk.Tarkov.GameWorld.Player;
global using eft_dma_radar.Silk.Tarkov.GameWorld.Quests;
global using eft_dma_radar.Silk.Config;
global using eft_dma_radar.Silk.Tarkov.Unity.Collections;
global using eft_dma_radar.Silk.UI;
global using eft_dma_radar.Silk.UI.Controls;
global using eft_dma_radar.Silk.UI.Panels;
global using eft_dma_radar.Silk.UI.ESP;
global using eft_dma_radar.Silk.UI.Maps;
global using eft_dma_radar.Silk.UI.Presets;
global using eft_dma_radar.Silk.Tarkov.Features.MemoryWrites;
